global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow:8001']
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:8001']
